# :warning: *{{ .Report.Level | upper }} ({{ .Report.App }}{{ if .Report.Instance }}/{{ .Report.Instance }}{{ end }}):* {{ .Report.Subject }}
---
{{ .Report.Body }}
```spoiler Report actions
[Inspect report]({{ .Info.PublicPath }}/report/{{ .Report.ID }})
[Resolve report]({{ .Info.PublicPath }}/resolve/{{ .Report.ID }}?user_id=1)
```
*Generated by {{ .NotifierName }}/Conomi{{ if .Info.Build.Version }} {{ .Info.Build.Version }}{{ end }}*