# {{ .Report.Severity | severityToEmoji }} {{ .Report.Severity.String | upper }}: {{ .Report.Subject }}
## {{ .Report | mkReportSourceIDLabel }}

{{ .Report.Body }}
{{ if and .Info.PublicPath .Report.ID }}
```spoiler Report actions
[Inspect report]({{ .Info.PublicPath }}/detail/{{ .Report.ID }})
[Resolve report]({{ .Info.PublicPath }}/resolve-since/{{ .Report.ID }}?user_id=1)
```
{{ end }}

*Generated by {{ .NotifierName }}/Conomi{{ if .Info.Build.Version }} {{ .Info.Build.Version }}{{ end }}*